### ISSUE TITLE
Finding both eggs and chicks

### ISSUE THREAD

**Issue by philipelbek** [philipelbek/NestboxesRungstedlund#11]
### Description

Som frivillig observatør er der en chance for, at jeg finder en rede hvor der både er æg og unger. Dette kan både være fordi at æggene er ved at klække et af gangen (ca. 1 om dagen), eller fordi resten af æggene er døde. Jeg skal have mulighed for at registrere både æggene og ungerne. Eventuelt som separate observationer. Hvis jeg indtaster to separate observationer, er det ungerne der vægter højest i forhold til hvornår kassen skal checkes igen af en ringmærker. 

### Tasks

- [ ] Kunne håndtere at der indtastes både æg og unger, hvor ungerne skal dikterer det næste kassecheck.

**Comment by asktheo** [comment]
Løsningsforslag: 
Der kan vælges status på en liste med interval til næste check således:
1. Tom : 21 d
2. Rede : 14 d
3. Æg : 7 d
4. Unger : 2 d

Unger er en status, som lige som de øvrige vil diktere næste kassecheck ud fra interval i dage (evt. konfigurerbart i senere version)

_Derudover_ og uanset, hvad der er valgt af status kan brugeren angive antal æg og antal unger samt artsnavn. 

Seneste status angiver næste check, dvs. bliver kassen prederet kan brugeren angive "Tom" igen, og så vil der være 21 d interval til næste check.

**Comment by asktheo** [comment]
Der kan angives antal af æg og unger i den nuværende test-version

**Comment by asktheo** [comment]
Antal af ringmrk unger overføres til nyt issue
