### ISSUE TITLE
Select the species from a list

### ISSUE THREAD

**Issue by asktheo** [philipelbek/NestboxesRungstedlund#17]
There is a limited list of species likely to breed in the boxes. 

Backend: Add them to a collection 
Frontend: Show the list on a dropdown list

Selecting a species should not be mandatory when adding a nestbox record

**Comment by asktheo** [comment]
@philipelbek , hvilke arter skal der være på listen, og hvad tænker I med dem, der enten er ubestemte eller noget andet end, hvad vi har på listen?

**Comment by philipelbek** [comment]
Arter:
Rødhals
Rødstjert
Blåmejse 
Musvit
Sumpmejse
Spætmejse 
Trælæber
Korttået Træløber 
Broget Fluesnapper 
Vendehals

Måske tilføj "Anden art". Hvis det er muligt at kommentere på en observation, kan man her skrive hvilken art. Alle fugle vil være dækket af listen, så her snakker vi flagermus, mus, spidsmus, egern etc.
