### ISSUE TITLE
When exists, show box orientation 

### ISSUE THREAD

**Issue by asktheo** [philipelbek/NestboxesRungstedlund#19]
For mig, der tjekker redekasser, kan jeg være i tvivl om, hvilken kasse jeg kigger I, da nummeret ikke altid er synligt, når jeg står på stigen. Kasser, der hænger tæt kan til gengæld have en forskellig retning - 
orientation. Ofte er der kun rede/æg/unger i en af dem, så jeg vil helst kun tjekke netop den igen og ikke de andre.
Jeg ønsker derfor retning angivet med 1-2 bogstaver, fx N, NØ, NV, V, SV ...

**Udviklernote**
Bruges pt. kun på et fåtal af kasser, så det vil være en fordel, at det ikke har sit eget felt i GUI, men blev sat bagved kassenummeret som label i app'en.

**Comment by asktheo** [comment]
@philipelbek har du noget at bemærke/tilføje?

**Comment by philipelbek** [comment]
Nej det synes jeg er godt.
