### ISSUE TITLE
Full report

### ISSUE THREAD

**Issue by philipelbek** [philipelbek/NestboxesRungstedlund#9]
### Description

Som administrator på redekasseprojektet vil jeg gerne kunne printe en rapport over sæsonen og give den videre til de frivillige.

### Tasks

- [ ] Print af rapport, som giver et godt overblik over sæsonen der er gået.

**Comment by sweco-dkthas** [comment]
Vil det være muligt at opfylde denne ved at lave en eksport-funktion i stedet ? Det kunne være til Excel, og så kan man arbejde videre med det, printe eller lave diagrammer og printe dem.

**Comment by philipelbek** [comment]
Ja det ville også være fint.
